words = [
    "arocc",
    "cbed",
    "cflags",
    "cglm",
    "deflt",
    "deinit",
    "eql",
    "fba",
    "fmacro",
    "framebuffers",
    "freetype",
    "glfw",
    "glsl",
    "glslang",
    "glslc",
    "infos",
    "khr",
    "khronos",
    "lifecycle",
    "msaa",
    "multisample",
    "multisampling",
    "ndc",
    "nixos",
    "nixpkgs",
    "numtide",
    "oom",
    "optionals",
    "pkgs",
    "pkill",
    "programmatically",
    "raii",
    "shader",
    "shaderc",
    "shaders",
    "spir",
    "spir-v",
    "spv",
    "srgb",
    "stdenv",
    "subpass",
    "swapchain",
    "unorm",
    "workson",
    "zeditor",
    "zls",
    "zon",
]
ignore_paths = ["flake.lock"]
