words = [
    "arocc",
    "cbed",
    "cloc",
    "dcover",
    "dedup",
    "deflt",
    "deinit",
    "deinitialized",
    "eql",
    "errdefer",
    "fba",
    "fovy",
    "framebuffers",
    "freetype",
    "glfw",
    "glm",
    "globbing",
    "glsl",
    "glslang",
    "glslc",
    "ibuf",
    "infos",
    "kcov",
    "khr",
    "khronos",
    "lve",
    "memcpy",
    "mkdir",
    "msaa",
    "mtl",
    "mtllib",
    "mul",
    "multisample",
    "nixos",
    "nixpkgs",
    "numtide",
    "oom",
    "optionals",
    "pkgs",
    "pkill",
    "programmatically",
    "raii",
    "renderable",
    "sfloat",
    "shader",
    "shaderc",
    "shaders",
    "spir",
    "spv",
    "srgb",
    "stb",
    "stdenv",
    "submatrix",
    "subpass",
    "swapchain",
    "tait",
    "tinyobj",
    "tinyobjloader",
    "tunables",
    "usemtl",
    "vbuf",
    "wasd",
    "workson",
    "xdg",
    "yxz",
    "zeditor",
    "zls",
    "zon",
]
ignore_paths = ["flake.lock", "build.zig.zon", "models/**/*", "zig-pkg/**/*"]
