name: build test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    #runs-on: ${{matrix.os}}
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # Install Nix and use that to run our tests so our environment matches exactly.
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # Run our checks to catch quick issues
      - run: nix flake check

      - name: spellcheck
        run: nix develop -c codebook-lsp lint .

      - name: build & test
        run: nix develop -c zig build test --summary all
