name: build test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Install devenv
        run: nix profile add github:NixOS/nixpkgs/549bd84d6279f9852cae6225e372cc67fb91a4c1#devenv

      - name: Evaluate flake
        run: nix flake check --no-build

      - name: spellcheck
        run: devenv shell -- codebook-lsp lint --unique -s .

      - name: lint (zlinter)
        run: devenv shell -- zig build lint

      - name: build & test
        run: devenv shell -- zig build test --summary all

      - name: Measure test coverage
        run: devenv shell -- zig-cov test --format=github --include=src/
